apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hhza
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hhza
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hhza
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hhza
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hhza
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uwtl-tenant/rhtap-demo-app/hacbs-test-project-hhza@sha256:ebfedd7227fe5aabcb37ecda87237570b5e3f75f2822f221ac0b147a3a748f65
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
