apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-hhza
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uwtl-tenant/rhtap-demo-app/hacbs-test-project-hhza@sha256:ebfedd7227fe5aabcb37ecda87237570b5e3f75f2822f221ac0b147a3a748f65
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
